image: Visual Studio 2015
platform: x64
environment:
  myuser:
    secure: BNlXevLtF9e2aPA67RkRlg==
  mypass:
    secure: UVcVBPUuJmH6Dargd2JZHitYoqNavVuBWWeJ8fvarLfSahvVhAAlXsnO2roo/75L
  global:
    PYTHONHASHSEED: "0"
    MINICONDA_PYTHON: "C:\\Miniconda36-x64"
    MSSdk: "1"
    SET_DISTUTILS_SDK: "1"

  matrix:
    - CONDA_PY: "35"
      CONDA_NPY: "114"
    - CONDA_PY: "36"
      CONDA_NPY: "114"
    - CONDA_PY: "37"
      CONDA_NPY: "114"

install:
  - cmd: '"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" %PLATFORM%'
  - ps: if ($env:PLATFORM -eq "x64") { $env:CONDA = "$env:CONDA-x64" }
  - "SET PATH=%MINICONDA_PYTHON%;%MINICONDA_PYTHON%\\Scripts;%PATH%;"
  - conda config --add channels conda-forge
  - conda install -yq conda-build

build: false

test_script:
  - conda build -q devtools/conda-recipe %CONDA_NPY%"
