package:
  name: bhmm-dev
  version: 0.0.0

source:
  path: ../..

build:
  number: 0
  script: pip install .

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
    - scipy
    - msmtools
    - pip

  run:
    - python
    - cython
    - numpy
    - scipy
    - msmtools

test:
  source_files:
    - conftest.py
  requires:
    - pytest
  imports:
    - bhmm
  commands:
    - pytest --pyargs bhmm -s -v --doctest-modules

about:
  home: https://github.com/choderalab/bhmm
  license: GNU Lesser General Public License v3 or later (LGPLv3+)
  summary: Bayesian hidden Markov models for analysis of single-molecule trajectory data
