
# This file is automatically generated by setup.py
short_version = '0.1.0'
version = '0.1.0'
full_version = '0.1.0.dev-0a85b1e'
git_revision = '0a85b1ea12cff00f58ce4d1e2cf011bd1c357269'
release = False

if not release:
    version = full_version
