
# This file is automatically generated by setup.py
short_version = '0.1.0'
version = '0.1.0'
full_version = '0.1.0.dev-9bcdea5'
git_revision = '9bcdea56d748236f6bdcd83a59cbd852d8a86c3a'
release = False

if not release:
    version = full_version
