
# This file is automatically generated by setup.py
short_version = '0.1.0'
version = '0.1.0'
full_version = '0.1.0.dev-7a24668'
git_revision = '7a246689d870866734cf4f89ba4c2fad9d1fdeb2'
release = False

if not release:
    version = full_version
